name: Build and go to Releases .deb package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+' # Триггер для тега, чтобы туда попадала версия пакета.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev make devscripts debhelper

      - name: Build .deb package
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          make build
          PACKAGE_NAME=$(find .. -type f -name "*.deb" | head -n 1)
          echo $PACKAGE_NAME
          NEW_NAME="fastapi-app_${VERSION}_amd64.deb"
          cp $PACKAGE_NAME ./$NEW_NAME
          echo "Package renamed and moved to $NEW_NAME"

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: fastapi-app_${{ env.VERSION }}_amd64.deb

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: deb-package

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Release of version ${{ github.ref }}
          files: fastapi-app_${{ github.ref_name }}_amd64.deb
          draft: false
          prerelease: false

