name: Build and Release .deb Package
on:
  push:
    tags:
      - '[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev make devscripts debhelper

      - name: Build .deb package
        run: |
          make build
          PACKAGE_NAME=$(ls *.deb | head -n 1)
          echo "Original package name: $PACKAGE_NAME"
          echo "Version: $VERSION"
          NEW_NAME="fastapi-app_${VERSION}_amd64.deb"
          echo "New package name: $NEW_NAME"
          mv $PACKAGE_NAME $NEW_NAME
          echo "DEB_PACKAGE=$NEW_NAME" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: ${{ env.DEB_PACKAGE }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: deb-package

      - name: List files
        run: ls -l

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: |
            Release of version ${{ github.ref_name }}.
          artifacts: "*.deb"
          draft: false
          prerelease: false
